parameters:
  - name: workloadSettings
    type: object

stages:
  - stage: build
    jobs:
      - template: /common/pipelines/03-jobs/iac.build.job.yml
        parameters:
          workloadSettings: ${{ parameters.workloadSettings }}