parameters:
  - name: workloadSettings
    type: object

stages:

  - ${{ each env in parameters.workloadSettings.environments }}:
      - ${{ each stage in parameters.workloadSettings.stages }}:
          - stage: ${{ env.name }}_${{ replace(replace(stage.infrastructure.iac.name, '-', '_'), '.', '_') }}
            variables:
              - template: /${{ parameters.workloadSettings.configurationFilePath }}/environments/vars-${{ env.name }}.yml@self
              
              - name: lastWorkloadInStage
                value: ${{ stage.infrastructure.iac.lastWorkloadInStage }}

              - name: primaryEnvironment
                value: ${{ env.primaryEnvironment }}
              - name: envDependsOn
                value: ${{ env.dependsOn }}
              - name: stageDependsOn
                value: ${{ stage.infrastructure.iac.dependsOn }}
              - name: stagePreRequisiteStage
                value: ${{ stage.infrastructure.iac.preRequisiteStage }}


            displayName: '${{ env.displayName }} - ${{ stage.infrastructure.iac.displayName }}'

          #   # primary environment and does not have workload dependency
          #   ${{ if and(eq(env.primaryEnvironment, 'true'), eq(stage.infrastructure.iac.dependsOn, '')) }}:
            
          #     dependsOn: build_${{ stage.infrastructure.iac.name }}

          #   # primary environment and has workload dependency
          #   ${{ elseif and(eq(env.primaryEnvironment, 'true'), ne(stage.infrastructure.iac.dependsOn, '')) }}:
        
          #     dependsOn:
          #       - build_${{ stage.infrastructure.iac.name }}
          #       - ${{ env.name }}_${{ stage.infrastructure.iac.dependsOn }}
            
          #   # non-primary environment and does not have workload dependency
          #   ${{ elseif and(ne(env.primaryEnvironment, 'true'), eq(stage.infrastructure.iac.dependsOn, '')) }}:
          #     dependsOn:
          #       # check if last in stage to depend on previous environment deployment
          #       - ${{ each dependencyStage in parameters.workloadSettings.stages }}:
          #           # get the stage which has lastInStage true and set dependsOn to that environment deployment
          #           - ${{ if ne(dependencyStage.infrastructure.iac.preRequisiteStage, 'true') }}:
          #               - ${{ env.dependsOn }}_${{ dependencyStage.infrastructure.iac.name }}
          
          #  # non-primary environment and has workload dependency            
          #   # ${{ else }}:
          #   ${{ elseif and(ne(env.primaryEnvironment, 'true'), eq(stage.infrastructure.iac.dependsOn, 'false')) }}:
          #     dependsOn:
          #       - ${{ env.dependsOn }}_${{ stage.infrastructure.iac.name }}

          #   # non-primary environment and, workload dependency and preRequisiteStage not defined
          #   ${{ elseif eq(stage.infrastructure.iac.preRequisiteStage, '') }}:
          #     dependsOn:
          #       - ${{ env.name }}_${{ stage.infrastructure.iac.dependsOn }}

            # check if environment is primary 
            ${{ if eq(env.primaryEnvironment, 'true') }}:
              # does not have workload dependency
              ${{ if ne(stage.infrastructure.iac.dependsOn, '') }}:
                dependsOn:
                  - build_${{ stage.infrastructure.iac.name }}
                  - ${{ env.name }}_${{ stage.infrastructure.iac.dependsOn }}

              # primary environment and has workload dependency
              ${{ else }}:          
                dependsOn: build_${{ stage.infrastructure.iac.name }}               
                
            
            ${{ else }}:

              # non-primary environment and does not have workload dependency
              ${{ elseif and(ne(env.primaryEnvironment, 'true'), eq(stage.infrastructure.iac.dependsOn, '')) }}:
                dependsOn:
                  # check if last in stage to depend on previous environment deployment
                  - ${{ each dependencyStage in parameters.workloadSettings.stages }}:
                      # get the stage which has lastInStage true and set dependsOn to that environment deployment
                      - ${{ if ne(dependencyStage.infrastructure.iac.preRequisiteStage, 'true') }}:
                          - ${{ env.dependsOn }}_${{ dependencyStage.infrastructure.iac.name }}
            
            # non-primary environment and has workload dependency            
              # ${{ else }}:
              ${{ elseif and(ne(env.primaryEnvironment, 'true'), eq(stage.infrastructure.iac.dependsOn, 'false')) }}:
                dependsOn:
                  - ${{ env.dependsOn }}_${{ stage.infrastructure.iac.name }}

              # non-primary environment and, workload dependency and preRequisiteStage not defined
              ${{ elseif eq(stage.infrastructure.iac.preRequisiteStage, '') }}:
                dependsOn:
                  - ${{ env.name }}_${{ stage.infrastructure.iac.dependsOn }}

            jobs:
              - template: /common/pipelines/03-jobs/iac.deploy.job.yml
                parameters:
                  workloadSettings: ${{ parameters.workloadSettings }}                  
                  jobSettings:
                    environment: ${{ env.name }}
                    stage: ${{ stage }}
                    

