parameters:
  - name: workloadSettings
    type: object

stages:
  - ${{ each env in parameters.workloadSettings.environments }}:
      - ${{ each stage in parameters.workloadSettings.stages }}:
          - stage: ${{ env.name }}_${{ replace(replace(stage.infrastructure.iac.name, '-', '_'), '.', '_') }}
            displayName: Deploy ${{ env.displayName }} - ${{ stage.infrastructure.iac.name }}
            dependsOn: ${{ env.dependsOn }}_${{ parameters.workloadSettings.name }}            
            
            variables:
              - template: /${{ parameters.workloadSettings.configurationFilePath }}/pipelines/vars-${{ env.name }}.yml@self
              - template: /common/pipelines/_config/release-engine.config.yml@release-engine

            jobs:
              - template: /common/pipelines/03-jobs/iac.deploy.job.yml
                parameters:
                  workloadSettings: ${{ parameters.workloadSettings }}                  
                  jobSettings:
                    environment: ${{ env.name }}
                    stage: ${{ stage }}

