parameters:
  - name: workloadSettings
    type: object

stages:
  - stage: build_${{ parameters.workloadSettings.name }}
    displayName: Build - ${{ parameters.workloadSettings.name }}
    dependsOn:
    variables:
      - template: /common/pipelines/_config/release-engine.config.yml@release-engine
    jobs:
      - template: /common/pipelines/03-jobs/iac.build.job.yml
        parameters:
          workloadSettings: ${{ parameters.workloadSettings }}
