parameters:
  - name: patternSettings
    type: object

stages:
  - template: /pipelines/02-stages/iac.build.stage.yml
    parameters:
      patternSettings: ${{ parameters.patternSettings }}

  - template: /pipelines/02-stages/iac.deploy.stage.yml
    parameters:
      patternSettings: ${{ parameters.patternSettings }}
  
  - stage: debug_stage_release_engine
    displayName: Debug - Release Engine
    condition: eq( variables['System.Debug'], 'true' )
    dependsOn: []
    jobs:
      - job: debug_job
        displayName: Debug Job
        steps:
        - powershell: |
            # Shows all configurations for debugging purposes of patternSettings
            Write-Host "\nParameters:"
            Write-Host '${{ convertToJson(parameters) }}'
            Write-Host "\nVariables:"
            Get-ChildItem env:
          displayName: Debug - Display Settings and Environment Variables