parameters:
  - name: workloadSettings
    type: object

stages:
  - stage: debug_stage_release_engine
    displayName: Debug Stage
    condition: eq( variables['System.Debug'], 'true' )
    jobs:
      - job: debug_job
        displayName: Debug Job
        steps:
        - powershell: |
            # Shows all configurations for debugging purposes of workloadSettings
            Write-Host "\nParameters:"
            Write-Host '${{ convertToJson(parameters) }}'
            Write-Host "\nVariables:"
            Get-ChildItem env:
          displayName: Display Settings and Environment Variables
          
  - template: /common/pipelines/02-stages/iac.build.stage.yml
    parameters:
      workloadSettings: ${{ parameters.workloadSettings }}

  - template: /common/pipelines/02-stages/iac.deploy.stage.yml
    parameters:
      workloadSettings: ${{ parameters.workloadSettings }}
  
