parameters:
  - name: deploymentSettings
    type: object

variables:
  # SPN of the lowest environment.
  # It is used for validate the pipeline run, and will be overridden by the correct SPN of each environment on runtime
  # Can be set on configuration level parameters or as environment variable in the pipeline execution context
  - name: serviceConnection
    value: IacServiceConnection 

stages:
  - template: /pipelines/01-orchestrators/pattern.orchestrator.yml
    parameters:
      patternSettings:
        name: resource_group_scope_pattern
        configurationFilePath: ${{ parameters.deploymentSettings.configurationFilePath }}
        environments: ${{ parameters.deploymentSettings.environments }}
        patternArtifactsPath: /patterns/templates/iac/resource_group_scope_pattern                                
        # Indicates if this is an builtin pattern in the release-engine-core repo
        # Options: "internal" | "external" | "" (empty string)
        patternContext: internal
        configurationPipelineContext: ${{ parameters.deploymentSettings.configurationPipelineContext }}
        
        stages:
          - infrastructure:
              iac:
                name: resource_group_scope_pattern
                displayName: Single Stage Example
                deploymentScope: ResourceGroup
                serviceConnection: $(serviceConnection)
                iacMainFileName: resource_group_scope_pattern.bicep
                iacParameterFileName: /parameters/resource_group_scope_pattern.parameters.json
                resourceGroupName: $(resourceGroupName)
                subscriptionId: $(subscriptionId)

 # This debug stage is optional and can be used to output parameters and variables for troubleshooting purposes
 # The debug stage can be omitted by commenting it out
  - stage: debug_stage_pattern
    displayName: Debug - Pattern Settings
    condition: eq( variables['System.Debug'], 'true' )
    dependsOn: []
    jobs:
      - job: debug_job
        displayName: Debug Job
        steps:
        - powershell: |
            # Shows all configurations for debugging purposes of patternSettings
            Write-Host "\nParameters:"
            Write-Host '${{ convertToJson(parameters) }}'
            Write-Host "\nVariables:"
            Get-ChildItem env:
          displayName: Debug - Display Settings and Environment Variables