parameters:
  - name: platformWorkloadSettings
    type: object

variables:
  # Workload dedicated SPN of the lowest environment.
  # It is used for validate the pipeline run, and will be overridden by the correct SPN of each environment on runtime
  # Can be set on configuration level parameters or as environment variable in the pipeline execution context
  - name: serviceConnection
    value: IacServiceConnection 

stages:
  - template: /common/pipelines/01-orchestrators/alz.devops.workload.orchestrator.yml
    parameters:
      workloadSettings:
        name: resource_group_scope_pattern
        configurationFilePath: ${{ parameters.platformWorkloadSettings.configurationFilePath }}
        environments: ${{ parameters.platformWorkloadSettings.environments }}
        workloadArtifactsPath: /patterns/iac/resource_group_scope_pattern
        # repository: release-engine-core
        stages:
          - infrastructure:
              iac:
                name: resource_group_scope_pattern
                displayName: Single Stage Example
                deploymentScope: ResourceGroup
                serviceConnection: $(serviceConnection)
                iacMainFileName: resource_group_scope_pattern.bicep
                iacParameterFileName: /parameters/resource_group_scope_pattern.parameters.json
                resourceGroupName: $(resourceGroupName)
                subscriptionId: $(subscriptionId)

 # This debug stage is optional and can be used to output parameters and variables for troubleshooting purposes
 # The debug stage can be omitted by commenting it out
  - stage: debug_stage_workload
    displayName: Debug - Workload
    condition: eq( variables['System.Debug'], 'true' )
    dependsOn: []
    jobs:
      - job: debug_job
        displayName: Debug Job
        steps:
        - powershell: |
            # Shows all configurations for debugging purposes of workloadSettings
            Write-Host "\nParameters:"
            Write-Host '${{ convertToJson(parameters) }}'
            Write-Host "\nVariables:"
            Get-ChildItem env:
          displayName: Debug - Display Settings and Environment Variables