parameters:
  - name: workloadSettings
    type: object

jobs:
  - job: ${{ variables.workload }}_build
    displayName: Building IaC Artifacts
    variables:
      - template: ${{ parameters.workloadSettings.configurationFilePath }}/pipelines/metadata.yml@self
      - ${{ if eq( parameters.workloadSettings.workloadArtifactsPath, '') }}:
          - name: workloadArtifactsPath
            value: $(Pipeline.Workspace)/s/${{ parameters.workloadSettings.workloadDefinitionRepositoryName }}/src
      - ${{ else }}:
          - name: workloadArtifactsPath
            value: $(Pipeline.Workspace)/s/${{ parameters.workloadSettings.workloadDefinitionRepositoryName }}/${{ parameters.workloadSettings.workloadArtifactsPath }}

    steps:
      - checkout: self
        path: configurationCheckoutDirectory
      - checkout: release-engine
        path: releaseEngineCheckoutDirectory
      - checkout: workload
        path: workloadCheckoutDirectory

      - task: CopyFiles@2
        displayName: Copying Workload content
        inputs:
          # SourceFolder: $(workloadArtifactsPath)
          SourceFolder: $(Pipeline.Workspace)/workloadCheckoutDirectory          
          Contents: |
            **
            !tests/**
            !examples/**
            !workload.yml
          TargetFolder: $(build.artifactstagingdirectory)/$(workload)
          flattenFolders: false

      - task: CopyFiles@2
        displayName: Copying content from Configuration repository
        inputs:
          SourceFolder: $(Pipeline.Workspace)/configurationCheckoutDirectory/${{ parameters.workloadSettings.configurationFilePath }}
          Contents: |
            **
            !pipelines/**
          TargetFolder: $(build.artifactstagingdirectory)/$(workload)/$(configurationArtifactName)
          flattenFolders: false

      - task: CopyFiles@2
        displayName: Copying common content
        inputs:
          SourceFolder: $(Pipeline.Workspace)/releaseEngineCheckoutDirectory/common
          Contents: |
            **
            !tests/**
            !examples/**
            !pipelines/**
          TargetFolder: $(build.artifactstagingdirectory)/common
          flattenFolders: false

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: $(build.artifactstagingdirectory)/$(workload)
          artifact: $(workloadArtifactName)
          publishLocation: pipeline

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: $(build.artifactstagingdirectory)/common
          artifact: common
          publishLocation: pipeline
