resources:
  repositories:
  - repository: yaml-templates    
    type: git    
    name: plt-sep/pad-deployment_tools-yaml_templates
    ref: main

trigger: none
      
variables:
  - name: serviceConnection
    value: plt-sep-dev-sp001 # Must be replaced by the SPN of the lowest environment. It is used for validate the pipeline run, and will be overriden by the correct SPN of each environment 

pool:
  vmImage: 'ubuntu-latest'

extends: 
  template: /common/pipelines/01-workloads/alz.platform.workload.yml@yaml-templates  
  parameters:
    workloadSettings:
      configurationFilePath: /workloads/platform/_TEMPLATE-COPY-ME-design-area/CHANGE-ME-workload/examples/_config
      
      environments:
        - development
      deploymentScript:
        - name: Agent_ListDirectoryItems
          scriptExtension: ps1
          arguments:
        - name: Agent_ListEnvironmentVariables
          scriptExtension: ps1
          arguments: -Directory "$(Pipeline.Workspace)"