parameters:
  - name: workloadSettings
    type: object

jobs:
  - job: ${{ variables.workload }}_build
    displayName: Building IaC Artifacts
    variables:

      - name: configurationCheckoutDirectory
        value: configurationCheckoutDirectory

      # - name: workloadCheckoutDirectory
      #   value: workloadCheckoutDirectory

      - ${{ if eq(parameters.workloadSettings.workloadContext,'internal') }}:
          - name: workloadCheckoutDirectory
            value: releaseEngineCheckoutDirectory

      # - ${{ else }}:
      #     - name: workloadCheckoutDirectory
      #       value: workloadCheckoutDirectory

      - ${{ if eq(parameters.workloadSettings.configurationPipelineContext,'internal') }}:      
          - name: workloadCheckoutDirectory
            value: workloadCheckoutDirectory
      



      - ${{ if eq(parameters.workloadSettings.configurationPipelineContext,'internal') }}:
          - template: ${{ parameters.workloadSettings.configurationFilePath }}/metadata.yml
          - name: releaseEngineCheckoutDirectory
            value: configurationCheckoutDirectory
          

      - ${{ else }}:
          - template: ${{ parameters.workloadSettings.configurationFilePath }}/metadata.yml@self
          - name: releaseEngineCheckoutDirectory
            value: releaseEngineCheckoutDirectory            
          
      
    steps:
      # - checkout: self
      #   path: configurationCheckoutDirectory
      # - checkout: release-engine-core
      #   path: releaseEngineCheckoutDirectory
      # - checkout: workload
      #   path: workloadCheckoutDirectory

      - checkout: self
        path: configurationCheckoutDirectory
      
      # - ${{ if ne(coalesce(parameters.workloadSettings.repository,''), '') }}:
      - ${{ if ne(parameters.workloadSettings.workloadContext,'internal') }}:
          - checkout: workload
            path: workloadCheckoutDirectory
      - ${{ if ne(parameters.workloadSettings.configurationPipelineContext,'internal') }}:
          - checkout: release-engine-core
            path: releaseEngineCheckoutDirectory          

      - powershell: |
          # Shows all configurations for debugging purposes of workloadSettings          
          Write-Host "\nParameters:"
          Write-Host '${{ convertToJson(parameters) }}'
          Write-Host "\nVariables:"
          Get-ChildItem env:

          tree /F $(Pipeline.Workspace)
        displayName: Debug - Display Settings and Environment Variables
        condition: eq( variables['System.Debug'], 'true' )

      - task: CopyFiles@2
        displayName: Copying content from Configuration repository
        inputs:
          SourceFolder: $(Pipeline.Workspace)/configurationCheckoutDirectory/${{ parameters.workloadSettings.configurationFilePath }}
          Contents: |
            **
            !pipelines/**
          TargetFolder: $(build.artifactstagingdirectory)/$(workload)/configuration
          flattenFolders: false

      - task: CopyFiles@2
        displayName: Copying Workload content
        inputs:
          SourceFolder: $(Pipeline.Workspace)/$(workloadCheckoutDirectory)/${{ parameters.workloadSettings.workloadArtifactsPath }}
          Contents: |
            **
            !tests/**
            !examples/**
            !workload.yml
          TargetFolder: $(build.artifactstagingdirectory)/$(workload)
          flattenFolders: false

      - task: CopyFiles@2
        displayName: Copying common content
        inputs:
          SourceFolder: $(Pipeline.Workspace)/$(releaseEngineCheckoutDirectory)/common
          Contents: |
            **
            !tests/**
            !examples/**
            !pipelines/**
          TargetFolder: $(build.artifactstagingdirectory)/common
          flattenFolders: false

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: $(build.artifactstagingdirectory)/$(workload)
          artifact: $(workload)
          publishLocation: pipeline

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: $(build.artifactstagingdirectory)/common
          artifact: common
          publishLocation: pipeline
